export interface Country {
    code: string;
    pt: string;
    en: string;
}

export const COUNTRIES: Country[] = [
    { code: 'AF', pt: 'AFEGANISTÃO', en: 'AFGHANISTAN' },
    { code: 'ZA', pt: 'ÁFRICA DO SUL', en: 'SOUTH AFRICA' },
    { code: 'AL', pt: 'ALBÂNIA', en: 'ALBANIA' },
    { code: 'DE', pt: 'ALEMANHA', en: 'GERMANY' },
    { code: 'AD', pt: 'ANDORRA', en: 'ANDORRA' },
    { code: 'AO', pt: 'ANGOLA', en: 'ANGOLA' },
    { code: 'AI', pt: 'ANGUILLA', en: 'ANGUILLA' },
    { code: 'AQ', pt: 'ANTÁRTIDA', en: 'ANTARCTICA' },
    { code: 'AG', pt: 'ANTÍGUA E BARBUDA', en: 'ANTIGUA AND BARBUDA' },
    { code: 'SA', pt: 'ARÁBIA SAUDITA', en: 'SAUDI ARABIA' },
    { code: 'DZ', pt: 'ARGÉLIA', en: 'ALGERIA' },
    { code: 'AR', pt: 'ARGENTINA', en: 'ARGENTINA' },
    { code: 'AM', pt: 'ARMÊNIA', en: 'ARMENIA' },
    { code: 'AW', pt: 'ARUBA', en: 'ARUBA' },
    { code: 'AU', pt: 'AUSTRÁLIA', en: 'AUSTRALIA' },
    { code: 'AT', pt: 'ÁUSTRIA', en: 'AUSTRIA' },
    { code: 'AZ', pt: 'AZERBAIJÃO', en: 'AZERBAIJAN' },
    { code: 'BS', pt: 'BAHAMAS', en: 'BAHAMAS' },
    { code: 'BD', pt: 'BANGLADESH', en: 'BANGLADESH' },
    { code: 'BB', pt: 'BARBADOS', en: 'BARBADOS' },
    { code: 'BH', pt: 'BAREIN', en: 'BAHRAIN' },
    { code: 'BE', pt: 'BÉLGICA', en: 'BELGIUM' },
    { code: 'BZ', pt: 'BELIZE', en: 'BELIZE' },
    { code: 'BJ', pt: 'BENIN', en: 'BENIN' },
    { code: 'BM', pt: 'BERMUDAS', en: 'BERMUDA' },
    { code: 'BY', pt: 'BIELORRÚSSIA', en: 'BELARUS' },
    { code: 'BO', pt: 'BOLÍVIA', en: 'BOLIVIA' },
    { code: 'BA', pt: 'BÓSNIA E HERZEGOVINA', en: 'BOSNIA AND HERZEGOVINA' },
    { code: 'BW', pt: 'BOTSUANA', en: 'BOTSWANA' },
    { code: 'BR', pt: 'BRASIL', en: 'BRAZIL' },
    { code: 'BN', pt: 'BRUNEI', en: 'BRUNEI DARUSSALAM' },
    { code: 'BG', pt: 'BULGÁRIA', en: 'BULGARIA' },
    { code: 'BF', pt: 'BURKINA FASO', en: 'BURKINA FASO' },
    { code: 'BI', pt: 'BURUNDI', en: 'BURUNDI' },
    { code: 'BT', pt: 'BUTÃO', en: 'BHUTAN' },
    { code: 'CV', pt: 'CABO VERDE', en: 'CAPE VERDE' },
    { code: 'CM', pt: 'CAMARÕES', en: 'CAMEROON' },
    { code: 'KH', pt: 'CAMBOJA', en: 'CAMBODIA' },
    { code: 'CA', pt: 'CANADÁ', en: 'CANADA' },
    { code: 'QA', pt: 'CATAR', en: 'QATAR' },
    { code: 'KZ', pt: 'CAZAQUISTÃO', en: 'KAZAKHSTAN' },
    { code: 'TD', pt: 'CHADE', en: 'CHAD' },
    { code: 'CL', pt: 'CHILE', en: 'CHILE' },
    { code: 'CN', pt: 'CHINA', en: 'CHINA' },
    { code: 'CY', pt: 'CHIPRE', en: 'CYPRUS' },
    { code: 'CO', pt: 'COLÔMBIA', en: 'COLOMBIA' },
    { code: 'KM', pt: 'COMORES', en: 'COMOROS' },
    { code: 'CG', pt: 'CONGO', en: 'CONGO' },
    { code: 'CD', pt: 'CONGO (REP. DEM.)', en: 'CONGO (DEM. REP.)' },
    { code: 'KP', pt: 'COREIA DO NORTE', en: 'NORTH KOREA' },
    { code: 'KR', pt: 'COREIA DO SUL', en: 'SOUTH KOREA' },
    { code: 'CI', pt: 'COSTA DO MARFIM', en: 'IVORY COAST' },
    { code: 'CR', pt: 'COSTA RICA', en: 'COSTA RICA' },
    { code: 'HR', pt: 'CROÁCIA', en: 'CROATIA' },
    { code: 'CU', pt: 'CUBA', en: 'CUBA' },
    { code: 'CW', pt: 'CURAÇAO', en: 'CURACAO' },
    { code: 'DK', pt: 'DINAMARCA', en: 'DENMARK' },
    { code: 'DJ', pt: 'DJIBOUTI', en: 'DJIBOUTI' },
    { code: 'DM', pt: 'DOMINICA', en: 'DOMINICA' },
    { code: 'EG', pt: 'EGITO', en: 'EGYPT' },
    { code: 'SV', pt: 'EL SALVADOR', en: 'EL SALVADOR' },
    { code: 'AE', pt: 'EMIRADOS ÁRABES UNIDOS', en: 'UNITED ARAB EMIRATES' },
    { code: 'EC', pt: 'EQUADOR', en: 'ECUADOR' },
    { code: 'ER', pt: 'ERITREIA', en: 'ERITREA' },
    { code: 'SK', pt: 'ESLOVÁQUIA', en: 'SLOVAKIA' },
    { code: 'SI', pt: 'ESLOVÊNIA', en: 'SLOVENIA' },
    { code: 'ES', pt: 'ESPANHA', en: 'SPAIN' },
    { code: 'US', pt: 'ESTADOS UNIDOS', en: 'UNITED STATES' },
    { code: 'EE', pt: 'ESTÔNIA', en: 'ESTONIA' },
    { code: 'ET', pt: 'ETIÓPIA', en: 'ETHIOPIA' },
    { code: 'FJ', pt: 'FIJI', en: 'FIJI' },
    { code: 'PH', pt: 'FILIPINAS', en: 'PHILIPPINES' },
    { code: 'FI', pt: 'FINLÂNDIA', en: 'FINLAND' },
    { code: 'FR', pt: 'FRANÇA', en: 'FRANCE' },
    { code: 'GA', pt: 'GABÃO', en: 'GABON' },
    { code: 'GM', pt: 'GÂMBIA', en: 'GAMBIA' },
    { code: 'GH', pt: 'GANA', en: 'GHANA' },
    { code: 'GE', pt: 'GEÓRGIA', en: 'GEORGIA' },
    { code: 'GI', pt: 'GIBRALTAR', en: 'GIBRALTAR' },
    { code: 'GD', pt: 'GRANADA', en: 'GRENADA' },
    { code: 'GR', pt: 'GRÉCIA', en: 'GREECE' },
    { code: 'GL', pt: 'GROENLÂNDIA', en: 'GREENLAND' },
    { code: 'GP', pt: 'GUADALUPE', en: 'GUADELOUPE' },
    { code: 'GU', pt: 'GUAM', en: 'GUAM' },
    { code: 'GT', pt: 'GUATEMALA', en: 'GUATEMALA' },
    { code: 'GG', pt: 'GUERNSEY', en: 'GUERNSEY' },
    { code: 'GY', pt: 'GUIANA', en: 'GUYANA' },
    { code: 'GF', pt: 'GUIANA FRANCESA', en: 'FRENCH GUIANA' },
    { code: 'GN', pt: 'GUINÉ', en: 'GUINEA' },
    { code: 'GQ', pt: 'GUINÉ EQUATORIAL', en: 'EQUATORIAL GUINEA' },
    { code: 'GW', pt: 'GUINÉ-BISSAU', en: 'GUINEA-BISSAU' },
    { code: 'HT', pt: 'HAITI', en: 'HAITI' },
    { code: 'NL', pt: 'HOLANDA (PAÍSES BAIXOS)', en: 'NETHERLANDS' },
    { code: 'HN', pt: 'HONDURAS', en: 'HONDURAS' },
    { code: 'HK', pt: 'HONG KONG', en: 'HONG KONG' },
    { code: 'HU', pt: 'HUNGRIA', en: 'HUNGARY' },
    { code: 'YE', pt: 'IÊMEN', en: 'YEMEN' },
    { code: 'IN', pt: 'ÍNDIA', en: 'INDIA' },
    { code: 'ID', pt: 'INDONÉSIA', en: 'INDONESIA' },
    { code: 'IR', pt: 'IRÃ', en: 'IRAN' },
    { code: 'IQ', pt: 'IRAQUE', en: 'IRAQ' },
    { code: 'IE', pt: 'IRLANDA', en: 'IRELAND' },
    { code: 'IS', pt: 'ISLÂNDIA', en: 'ICELAND' },
    { code: 'IL', pt: 'ISRAEL', en: 'ISRAEL' },
    { code: 'IT', pt: 'ITÁLIA', en: 'ITALY' },
    { code: 'JM', pt: 'JAMAICA', en: 'JAMAICA' },
    { code: 'JP', pt: 'JAPÃO', en: 'JAPAN' },
    { code: 'JE', pt: 'JERSEY', en: 'JERSEY' },
    { code: 'JO', pt: 'JORDÂNIA', en: 'JORDAN' },
    { code: 'KW', pt: 'KUWAIT', en: 'KUWAIT' },
    { code: 'LA', pt: 'LAOS', en: 'LAOS' },
    { code: 'LS', pt: 'LESOTO', en: 'LESOTHO' },
    { code: 'LV', pt: 'LETÔNIA', en: 'LATVIA' },
    { code: 'LB', pt: 'LÍBANO', en: 'LEBANON' },
    { code: 'LR', pt: 'LIBÉRIA', en: 'LIBERIA' },
    { code: 'LY', pt: 'LÍBIA', en: 'LIBYA' },
    { code: 'LI', pt: 'LIECHTENSTEIN', en: 'LIECHTENSTEIN' },
    { code: 'LT', pt: 'LITUÂNIA', en: 'LITHUANIA' },
    { code: 'LU', pt: 'LUXEMBURGO', en: 'LUXEMBOURG' },
    { code: 'MO', pt: 'MACAU', en: 'MACAU' },
    { code: 'MK', pt: 'MACEDÔNIA DO NORTE', en: 'NORTH MACEDONIA' },
    { code: 'MG', pt: 'MADAGASCAR', en: 'MADAGASCAR' },
    { code: 'MY', pt: 'MALÁSIA', en: 'MALAYSIA' },
    { code: 'MW', pt: 'MALAWI', en: 'MALAWI' },
    { code: 'MV', pt: 'MALDIVAS', en: 'MALDIVES' },
    { code: 'ML', pt: 'MALI', en: 'MALI' },
    { code: 'MT', pt: 'MALTA', en: 'MALTA' },
    { code: 'MA', pt: 'MARROCOS', en: 'MOROCCO' },
    { code: 'MQ', pt: 'MARTINICA', en: 'MARTINIQUE' },
    { code: 'MU', pt: 'MAURÍCIO', en: 'MAURITIUS' },
    { code: 'MR', pt: 'MAURITÂNIA', en: 'MAURITANIA' },
    { code: 'MX', pt: 'MÉXICO', en: 'MEXICO' },
    { code: 'MM', pt: 'MYANMAR (BIRMÂNIA)', en: 'MYANMAR' },
    { code: 'FM', pt: 'MICRONÉSIA', en: 'MICRONESIA' },
    { code: 'MZ', pt: 'MOÇAMBIQUE', en: 'MOZAMBIQUE' },
    { code: 'MD', pt: 'MOLDÁVIA', en: 'MOLDOVA' },
    { code: 'MC', pt: 'MÔNACO', en: 'MONACO' },
    { code: 'MN', pt: 'MONGÓLIA', en: 'MONGOLIA' },
    { code: 'ME', pt: 'MONTENEGRO', en: 'MONTENEGRO' },
    { code: 'MS', pt: 'MONTSERRAT', en: 'MONTSERRAT' },
    { code: 'NA', pt: 'NAMÍBIA', en: 'NAMIBIA' },
    { code: 'NR', pt: 'NAURU', en: 'NAURU' },
    { code: 'NP', pt: 'NEPAL', en: 'NEPAL' },
    { code: 'NI', pt: 'NICARÁGUA', en: 'NICARAGUA' },
    { code: 'NE', pt: 'NÍGER', en: 'NIGER' },
    { code: 'NG', pt: 'NIGÉRIA', en: 'NIGERIA' },
    { code: 'NO', pt: 'NORUEGA', en: 'NORWAY' },
    { code: 'NC', pt: 'NOVA CALEDÔNIA', en: 'NEW CALEDONIA' },
    { code: 'NZ', pt: 'NOVA ZELÂNDIA', en: 'NEW ZEALAND' },
    { code: 'OM', pt: 'OMÃ', en: 'OMAN' },
    { code: 'PW', pt: 'PALAU', en: 'PALAU' },
    { code: 'PS', pt: 'PALESTINA', en: 'PALESTINE' },
    { code: 'PA', pt: 'PANAMÁ', en: 'PANAMA' },
    { code: 'PG', pt: 'PAPUA NOVA GUINÉ', en: 'PAPUA NEW GUINEA' },
    { code: 'PK', pt: 'PAQUISTÃO', en: 'PAKISTAN' },
    { code: 'PY', pt: 'PARAGUAI', en: 'PARAGUAY' },
    { code: 'PE', pt: 'PERU', en: 'PERU' },
    { code: 'PF', pt: 'POLINÉSIA FRANCESA', en: 'FRENCH POLYNESIA' },
    { code: 'PL', pt: 'POLÔNIA', en: 'POLAND' },
    { code: 'PR', pt: 'PORTO RICO', en: 'PUERTO RICO' },
    { code: 'PT', pt: 'PORTUGAL', en: 'PORTUGAL' },
    { code: 'KE', pt: 'QUÊNIA', en: 'KENYA' },
    { code: 'KG', pt: 'QUIRGUISTÃO', en: 'KYRGYZSTAN' },
    { code: 'GB', pt: 'REINO UNIDO', en: 'UNITED KINGDOM' },
    { code: 'CF', pt: 'REPÚBLICA CENTRO-AFRICANA', en: 'CENTRAL AFRICAN REPUBLIC' },
    { code: 'DO', pt: 'REPÚBLICA DOMINICANA', en: 'DOMINICAN REPUBLIC' },
    { code: 'CZ', pt: 'REPÚBLICA TCHECA', en: 'CZECH REPUBLIC' },
    { code: 'RE', pt: 'REUNIÃO', en: 'REUNION' },
    { code: 'RO', pt: 'ROMÊNIA', en: 'ROMANIA' },
    { code: 'RW', pt: 'RUANDA', en: 'RWANDA' },
    { code: 'RU', pt: 'RÚSSIA', en: 'RUSSIA' },
    { code: 'EH', pt: 'SAARA OCIDENTAL', en: 'WESTERN SAHARA' },
    { code: 'WS', pt: 'SAMOA', en: 'SAMOA' },
    { code: 'AS', pt: 'SAMOA AMERICANA', en: 'AMERICAN SAMOA' },
    { code: 'SM', pt: 'SAN MARINO', en: 'SAN MARINO' },
    { code: 'LC', pt: 'SANTA LÚCIA', en: 'SAINT LUCIA' },
    { code: 'ST', pt: 'SÃO TOMÉ E PRÍNCIPE', en: 'SAO TOME AND PRINCIPE' },
    { code: 'SN', pt: 'SENEGAL', en: 'SENEGAL' },
    { code: 'SL', pt: 'SERRA LEOA', en: 'SIERRA LEONE' },
    { code: 'RS', pt: 'SÉRVIA', en: 'SERBIA' },
    { code: 'SC', pt: 'SEYCHELLES', en: 'SEYCHELLES' },
    { code: 'SG', pt: 'SINGAPURA', en: 'SINGAPORE' },
    { code: 'SY', pt: 'SÍRIA', en: 'SYRIA' },
    { code: 'SO', pt: 'SOMÁLIA', en: 'SOMALIA' },
    { code: 'LK', pt: 'SRI LANKA', en: 'SRI LANKA' },
    { code: 'SZ', pt: 'SUAZILÂNDIA (ESWATINI)', en: 'ESWATINI' },
    { code: 'SD', pt: 'SUDÃO', en: 'SUDAN' },
    { code: 'SS', pt: 'SUDÃO DO SUL', en: 'SOUTH SUDAN' },
    { code: 'SE', pt: 'SUÉCIA', en: 'SWEDEN' },
    { code: 'CH', pt: 'SUÍÇA', en: 'SWITZERLAND' },
    { code: 'SR', pt: 'SURINAME', en: 'SURINAME' },
    { code: 'TH', pt: 'TAILÂNDIA', en: 'THAILAND' },
    { code: 'TW', pt: 'TAIWAN', en: 'TAIWAN' },
    { code: 'TJ', pt: 'TAJIQUISTÃO', en: 'TAJIKISTAN' },
    { code: 'TZ', pt: 'TANZÂNIA', en: 'TANZANIA' },
    { code: 'TL', pt: 'TIMOR-LESTE', en: 'EAST TIMOR' },
    { code: 'TG', pt: 'TOGO', en: 'TOGO' },
    { code: 'TO', pt: 'TONGA', en: 'TONGA' },
    { code: 'TT', pt: 'TRINIDAD E TOBAGO', en: 'TRINIDAD AND TOBAGO' },
    { code: 'TN', pt: 'TUNÍSIA', en: 'TUNISIA' },
    { code: 'TM', pt: 'TURCOMENISTÃO', en: 'TURKMENISTAN' },
    { code: 'TR', pt: 'TURQUIA', en: 'TURKEY' },
    { code: 'TV', pt: 'TUVALU', en: 'TUVALU' },
    { code: 'UA', pt: 'UCRÂNIA', en: 'UKRAINE' },
    { code: 'UG', pt: 'UGANDA', en: 'UGANDA' },
    { code: 'UY', pt: 'URUGUAI', en: 'URUGUAY' },
    { code: 'UZ', pt: 'UZBEQUISTÃO', en: 'UZBEKISTAN' },
    { code: 'VU', pt: 'VANUATU', en: 'VANUATU' },
    { code: 'VA', pt: 'VATICANO', en: 'VATICAN CITY' },
    { code: 'VE', pt: 'VENEZUELA', en: 'VENEZUELA' },
    { code: 'VN', pt: 'VIETNÃ', en: 'VIETNAM' },
    { code: 'ZM', pt: 'ZÂMBIA', en: 'ZAMBIA' },
    { code: 'ZW', pt: 'ZIMBÁBUE', en: 'ZIMBABWE' }
];